[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

; Flash
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv

; Monitor
monitor_speed = 115200

; Build flags - add all src subdirs to include path
build_flags =
    -DBOARD_HAS_PSRAM
    -I src
    -I src/engine
    -I src/vfpga
    -I src/io
    -I src/hdl
    -I src/riscv
    -I src/benchmarks
    -I src/tests
