/*
   Golden DUT for simulation + synthesis: VerilogEmitter output
   for the 8-bit counter mini-HDL design (see test_hdl.cpp).
   Included by tb_counter.v; synthesized by the CI Yosys smoke test.
*/
// Generated by VFPGA-S3 VerilogEmitter (AST -> behavioral Verilog).
// NOTE: '+' synthesizes WITH carry; the VFPGA fabric maps it carry-less (0x6666).
module counter(clock, reset, count);
input clock;
input reset;
output [7:0] count;
reg [7:0] count_reg;
    always @(posedge clock) begin
        if (reset)
            count_reg <= 0;
        else
            count_reg <= (count_reg + 1);
    end
    assign count = count_reg;
endmodule
