/*
   Self-contained Icarus Verilog testbench.
   DUT below is the verbatim VerilogEmitter golden output for
    "module and_gate; input a; input b; output y; assign y = a & b; endmodule"
   Run: iverilog -o /tmp/tb_and host_test/tb_and.v && vvp /tmp/tb_and
   DUT: VerilogEmitter golden output (see test_hdl.cpp "AND gate Verilog emission").
   Generated by VFPGA-S3 VerilogEmitter (AST -> behavioral Verilog).
   NOTE: '+' synthesizes WITH carry; the toolchain builds matching ripple-carry logic (XOR3/MAJ3).
*/
module and_gate(a, b, y);
input a;
input b;
output y;
    assign y = (a & b);
endmodule

module tb_and;
reg a, b;
wire y;
and_gate dut(a, b, y);
integer fails;
initial begin
    fails = 0;
    a = 0; b = 0; #10; if (y !== 0) fails = fails + 1;
    a = 0; b = 1; #10; if (y !== 0) fails = fails + 1;
    a = 1; b = 0; #10; if (y !== 0) fails = fails + 1;
    a = 1; b = 1; #10; if (y !== 1) fails = fails + 1;
    if (fails == 0) $display("TB-AND PASS");
    else $display("TB-AND FAIL %0d", fails);
    $finish;
end
endmodule
