/*
   Self-contained Icarus Verilog testbench.
   DUT below is the verbatim VerilogEmitter output for
    "module xor_gate; input a; input b; output y; assign y = a ^ b; endmodule"
   Run: iverilog -o /tmp/tb_xor host_test/tb_xor.v && vvp /tmp/tb_xor
   Generated by VFPGA-S3 VerilogEmitter (AST -> behavioral Verilog).
   NOTE: '+' synthesizes WITH carry; the toolchain builds matching ripple-carry logic (XOR3/MAJ3).
*/
module xor_gate(a, b, y);
input a;
input b;
output y;
    assign y = (a ^ b);
endmodule

module tb_xor;
reg a, b;
wire y;
xor_gate dut(a, b, y);
integer fails;
initial begin
    fails = 0;
    a = 0; b = 0; #10; if (y !== 0) fails = fails + 1;
    a = 0; b = 1; #10; if (y !== 1) fails = fails + 1;
    a = 1; b = 0; #10; if (y !== 1) fails = fails + 1;
    a = 1; b = 1; #10; if (y !== 0) fails = fails + 1;
    if (fails == 0) $display("TB-XOR PASS");
    else $display("TB-XOR FAIL %0d", fails);
    $finish;
end
endmodule
