// VCD writer implementation. See vcd.h.
#include "vcd.h"

#include <cstdio>
#include <map>

#include "trace.h"

// Deterministic printable ids starting at '!' (§16), base-94 past '~'.
static std::string var_id(size_t i) {
    std::string s;
    do {
        s += (char)('!' + (i % 94));
        i /= 94;
    } while (i > 0);
    return s;
}

static bool is_fabric(const std::string &name) {
    return !name.empty() && name[0] == '_';
}

// Split "base[N]" into base + index; returns false if not a bit net.
static bool split_bit(const std::string &name, std::string &base, int &idx) {
    size_t l = name.rfind('[');
    if (l == std::string::npos || name.back() != ']') return false;
    try {
        idx = std::stoi(name.substr(l + 1, name.size() - l - 2));
    } catch (...) { return false; }
    if (idx < 0 || idx > 1023) return false;
    base = name.substr(0, l);
    return true;
}

std::vector<VcdSignal> vcd_signals(const Simulator &sim,
                                   const std::vector<uint16_t> &nets) {
    // Preserve watch order; group name[N] nets into buses.
    std::vector<VcdSignal> out;
    std::map<std::string, size_t> bus_idx;  // base -> out index
    for (size_t k = 0; k < nets.size(); ++k) {
        const SimSignal *s = nullptr;
        for (size_t i = 0; i < sim.signal_count(); ++i)
            if (sim.signal(i).net_id == nets[k]) { s = &sim.signal(i); break; }
        if (!s) continue;
        std::string base;
        int idx = 0;
        if (split_bit(s->name, base, idx)) {
            auto it = bus_idx.find(base);
            if (it == bus_idx.end()) {
                VcdSignal g;
                g.net = s->net_id;
                g.name = "top." + base;
                g.width = idx + 1;
                g.bus_nets = std::vector<uint16_t>(idx + 1, 0);
                g.bus_nets[idx] = s->net_id;
                bus_idx[base] = out.size();
                out.push_back(g);
            } else {
                VcdSignal &g = out[it->second];
                if (idx + 1 > g.width) {
                    g.width = idx + 1;
                    g.bus_nets.resize(idx + 1, 0);
                }
                g.bus_nets[idx] = s->net_id;
            }
        } else {
            VcdSignal v;
            v.net = s->net_id;
            v.name = std::string(is_fabric(s->name) ? "top.fabric." : "top.") + s->name;
            v.width = 1;
            out.push_back(v);
        }
    }
    return out;
}

bool write_vcd(const char *path, const char *timescale,
               const std::vector<VcdSignal> &sigs,
               const std::vector<TraceSample> &samples) {
    FILE *f = fopen(path, "w");
    if (!f) return false;

    fprintf(f, "$date generated by vfpga-sim $end\n");
    fprintf(f, "$version VFPGA-S3 host simulator $end\n");
    fprintf(f, "$timescale %s $end\n", timescale);

    // net -> (var id, signal idx, bus bit or -1)
    std::map<uint16_t, std::pair<std::string, int> > id_of;
    std::map<uint16_t, int> bit_of;
    bool top_open = false, fab_open = false;
    auto open_top = [&]() {
        if (!top_open) { fprintf(f, "$scope module top $end\n"); top_open = true; }
    };
    for (size_t i = 0; i < sigs.size(); ++i) {
        const VcdSignal &s = sigs[i];
        std::string id = var_id(i);
        bool fab = s.name.find("top.fabric.") == 0;
        std::string short_name = fab ? s.name.substr(11) : s.name.substr(4);
        if (s.width == 1) {
            if (fab) {
                open_top();
                if (!fab_open) { fprintf(f, "$scope module fabric $end\n"); fab_open = true; }
                fprintf(f, "$var wire 1 %s %s $end\n", id.c_str(), short_name.c_str());
            } else {
                if (fab_open) { fprintf(f, "$upscope $end\n"); fab_open = false; }
                open_top();
                fprintf(f, "$var wire 1 %s %s $end\n", id.c_str(), short_name.c_str());
            }
            id_of[s.net] = std::make_pair(id, (int)i);
            bit_of[s.net] = -1;
        } else {
            if (fab_open) { fprintf(f, "$upscope $end\n"); fab_open = false; }
            open_top();
            fprintf(f, "$var wire %d %s %s $end\n", s.width, id.c_str(), short_name.c_str());
            for (int b = 0; b < s.width; ++b) {
                id_of[s.bus_nets[b]] = std::make_pair(id, (int)i);
                bit_of[s.bus_nets[b]] = b;
            }
        }
    }
    if (fab_open) fprintf(f, "$upscope $end\n");
    if (top_open) fprintf(f, "$upscope $end\n");
    fprintf(f, "$enddefinitions $end\n");

    // Change-ordered dump; buses re-emitted only when the bus value changes.
    std::map<uint16_t, uint32_t> cur;
    std::map<int, uint32_t> bus_cur;
    std::map<int, bool> bus_init;
    SimTime last_t = 0;
    bool first = true;
    for (size_t k = 0; k < samples.size(); ++k) {
        const TraceSample &sm = samples[k];
        if (id_of.find(sm.net) == id_of.end()) continue;
        if (first || sm.t != last_t) {
            fprintf(f, "#%lu\n", (unsigned long)sm.t);
            last_t = sm.t;
            first = false;
        }
        cur[sm.net] = sm.value & 1;
        int bit = bit_of[sm.net];
        const std::string &id = id_of[sm.net].first;
        int si = id_of[sm.net].second;
        if (bit < 0) {
            fprintf(f, "%u%s\n", cur[sm.net] ? 1 : 0, id.c_str());
        } else {
            uint32_t bv = bus_init[si] ? bus_cur[si] : 0;
            if (cur[sm.net]) bv |= (1U << bit);
            else bv &= ~(1U << bit);
            if (!bus_init[si] || bv != bus_cur[si]) {
                std::string bits;
                for (int b = sigs[(size_t)si].width - 1; b >= 0; --b)
                    bits += ((bv >> b) & 1) ? '1' : '0';
                fprintf(f, "b%s %s\n", bits.c_str(), id.c_str());
                bus_cur[si] = bv;
                bus_init[si] = true;
            }
        }
    }

    fclose(f);
    return true;
}
